### ISSUE TITLE
Is the ansible.cfg needed here? 

### ISSUE THREAD

**Issue by swapdisk** [swapdisk/lvm_snapshots#19]
@ygalblum, we ran into an issue where the `ansible.cfg` in this repo supersedes the one on the AAP/Tower server. Can we remove this file from the repo?

**Comment by ygalblum** [comment]
The `ansible.cfg` file is used for running the tests without having to install the collection on the tested machine. I can see that it is not packed into the collection, so I'm not sure why you even have it when running a playbook that uses the role. 

Having said that, since it is used for testing, I've moved it there and added a README describing how to run the test (#20)
